# Generated by Django 3.1.1 on 2020-09-30 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='auther',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communicate.article')),
            ],
        ),
    ]
