# Generated by Django 3.1.1 on 2020-09-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0002_auto_20200930_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
