# Generated by Django 3.1.1 on 2020-09-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communicate', '0005_answer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
